
export const USER_PENDING = 'USER_PENDING';
export const USER_PENDING_END = 'USER_PENDING_END';

export const USER_LOGIN_SUCSESS = 'USER_LOGIN_SUCSESS';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';

export const GET_MOVIES_SUCSESS = 'GET_MOVIES_SUCSESS';
export const GET_MOVIES_FAILED = 'GET_MOVIES_FAILED';

export const DELETE_MOVIES_SUCSESS = 'DELETE_MOVIES_SUCSESS';
export const DELETE_MOVIES_FAILED = 'DELETE_MOVIES_FAILED';
